version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - memory-game-network

  frontend:
    build: ./frontend
    ports:
      - "8081:8080"
    networks:
      - memory-game-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  memory-game-network:
    driver: bridge
