version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - memory-game-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/memorygame
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build: ./frontend
    ports:
      - "8081:8080"
    networks:
      - memory-game-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: memorygame
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - memory-game-network

networks:
  memory-game-network:
    driver: bridge
